name: Check generated TOCs

on:
  pull_request:
    paths:
      - "README.md"
      - "docs/BestPractices.md"

permissions:
  contents: read

jobs:
  doctoc:
    name: Doc TOC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 'lts/*'
      - name: Install doctoc
        run: npm i -g doctoc
      - name: Create README copy and diff with doctoc
        run: cp README.md README.md.tmp &&
          doctoc --title='## Table of Contents' --github README.md &&
          diff -q README.md README.md.tmp
      - name: Create "docs/BestPractices.md" copy and diff with doctoc
        run: cp docs/BestPractices.md docs/BestPractices.md.tmp &&
          doctoc --title='## Table of Contents' --github docs/BestPractices.md &&
          diff -q docs/BestPractices.md docs/BestPractices.md.tmp
